version: "3.12.3"

services:
  web:
    build: .
    container_name: django_wysiwyg_faqs
    command: gunicorn bharatfd.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=0
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery

  celery:
    build: .
    container_name: celery_worker
    command: celery -A bharatfd worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A bharatfd beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: